---
AWSTemplateFormatVersion: "2010-09-09"
Description:  (DataCollection) root stack for DataCollectionBus

Parameters:
  DataCollectionBucket:
    Type: String
  DataCollectionBucketKmsArn:
    Type: String
    Default: "N"
    Description: Enter KMS Arn if bucket is encrypted(Type N for SSE encryption)
  QuicksightServiceRole:
    Type: String
    Default: aws-quicksight-service-role-v0
    Description: The Quicksight Service role attached to QS, Default is aws-quicksight-service-role-v0
  QuickSightUser:
    Type: String
    Description: The QuickSight User that is allowed configure and manage the QS dashboard.
  POrgID:
    Type: String
    Description: The AWS Organizations ID for the organization that should be allowed to put events on the event bus.
  BackfillEvents:
    Default: "N"
    Type: String
    Description: (Optional) Backfill health events Y/N.
  AllowedIpRange:
    Default: "N"
    Type: String
    Description: (Optional) AllowedIpRange who can access EventDetailUrls, Type "N" to disable this.
  AuthorizationType:
    Default: "NONE"
    Type: String
    Description: (Optional) Specify a valid Default value for AuthorizationType. Valid values are ["NONE", "AWS_IAM", "CUSTOM", "COGNITO_USER_POOLS"], This is required if AllowedIpRange is supplied.
  ConfigAggregatorBucket:
    Default: "N"
    Type: String
    Description: (Optional) S3 Bucket where Config data is aggregated, Type "N" to disable this.
  Notification:
    Type: String
    Default: "N"
    Description: (Optional) Notificaiton Required? Type "N" to disable this.
  SlackChannelId:
    Type: String
    Default: "N"
    Description: (Optional) SlackChannelId. Type "N" to disable this.
  SlackWorkspaceId:
    Type: String
    Default: "N"
    Description: (Optional) SlackWorkspaceId. Type "N" to disable this.
  TeamId:
    Type: String
    Description: (Optional) The ID of the Microsoft Teams team to configure. Type "N" to disable this.
    Default: "N"
  TeamsTenantId:
    Type: String
    Description: (Optional) The ID of the Microsoft Teams tenant. Type "N" to disable this.
    Default: "N"
  TeamsChannelId:
    Type: String
    Description: (Optional) The ID of the Microsoft Teams channel to configure. Type "N" to disable this.
    Default: "N"

Resources:
  DataCollection:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/DataCollectionModule/DataCollectionStack.yaml
      Parameters:
        DataCollectionBucket: !Ref DataCollectionBucket
        DataCollectionBucketKmsArn: !Ref DataCollectionBucketKmsArn
        POrgID: !Ref POrgID

  DataSource:
    DependsOn: HealthEventMember
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/QSDataSource.yaml
      Parameters:
        DataCollectionBucket: !Ref DataCollectionBucket
        QuicksightServiceRole: !Ref QuicksightServiceRole
        ConfigAggregatorBucket: !Ref ConfigAggregatorBucket
        DataCollectionBucketKmsArn: !Ref DataCollectionBucketKmsArn

  HealthEventDetailsUrl:
    Condition: AllowedIpRange
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/HealthEventDetailUrl.yaml
      Parameters:
        DataCollectionBusArn: !GetAtt  DataCollection.Outputs.DataCollectionBusArn
        AllowedIpRange: !Ref AllowedIpRange
        AuthorizationType: !Ref AuthorizationType

  HealthEventNotification:
    Condition: Notification
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/HealthEventNotification.yaml
      Parameters:
        DataCollectionBusArn: !GetAtt  DataCollection.Outputs.DataCollectionBusArn
        SlackChannelId: !Ref SlackChannelId
        SlackWorkspaceId: !Ref SlackWorkspaceId
        TeamId: !Ref TeamId
        TeamsTenantId: !Ref TeamsTenantId
        TeamsChannelId: !Ref TeamsChannelId

  HealthEventMember:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/HealthEventMember.yaml
      Parameters:
        DataCollectionBusArn: !GetAtt  DataCollection.Outputs.DataCollectionBusArn
        BackfillEvents: !Ref BackfillEvents
        EventDetailUrl: !If [ AllowedIpRange, !GetAtt HealthEventDetailsUrl.Outputs.EventDetailApiEndpoint, "https://test" ]

  QSDataSetHealthEvent:
    DependsOn: HealthEventMember
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/QSDataSetHealthEvent.yaml
      Parameters:
        QuickSightUser: !Ref QuickSightUser
        DataSourceArn: !GetAtt DataSource.Outputs.DataSourceArn

  QSDataSourcePartition:
    Condition: ConfigAggregatorBucket
    DependsOn: HealthEventMember
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/QSDataSourcePartition.yaml
      Parameters:
        GlueConfigTable: !GetAtt DataSource.Outputs.GlueConfigTable
        GlueDatabaseDataCollection: !GetAtt DataSource.Outputs.GlueDatabaseDataCollection
        ConfigAggregatorBucket: !Ref ConfigAggregatorBucket
        DataCollectionBusArn: !GetAtt  DataCollection.Outputs.DataCollectionBusArn

  QSAnalysisHealthEvent:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://${DataCollectionBucket}.s3.amazonaws.com/DataCollection-metadata/AWSHealthModule/cfnTemplates/QSAnalysisHealthEvent.yaml
      Parameters:
        QSDataSetHealthEventArn: !GetAtt  QSDataSetHealthEvent.Outputs.QSDataSetHealthEventArn
        EventDetailUrl: !If [ AllowedIpRange, !GetAtt HealthEventDetailsUrl.Outputs.EventDetailApiEndpoint, "https://test" ]
        QuickSightUser: !Ref QuickSightUser

Conditions:
  Notification: !Equals [!Ref Notification, "Y"]
  AllowedIpRange: !Not [!Equals [!Ref AllowedIpRange, "N"]]
  ConfigAggregatorBucket: !Not [!Equals [!Ref ConfigAggregatorBucket, "N"]]

  