---
AWSTemplateFormatVersion: '2010-09-09'
Description: (AwsHealthEvents) Stack to create cross Account role in AWS Config aggregator account.

Parameters:
  AWSHealthEventEnrichLambdaRoleArn:
    Type: String
    Description: EnrichLambdaRole Arn from Central Account. You can get from stack in central account with HeidiDataCollection-<AccountID>-<region>-AWSHealthEventEnrich-<hash>

Resources:
  AWSHealthEventEnrichLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HeidiDataCollection-ConfigCrossAccount-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWSHealthEventEnrichLambdaRoleArn
            Action: sts:AssumeRole 
      Policies:
        - PolicyName: cloudwatch-logsAccess-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
        - PolicyName: AwshealtheventConfig-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - config:SelectAggregateResourceConfig
                Resource: "*"